---
- name: Prepare node
  hosts: localhost
  roles:
    - role: robertdebock.openssh
      become: true
      tags:
        - openssh
    - role: terminator
      tags:
        - terminal
    - role: tmux
      tags:
        - terminal
    - role: zsh
      tags:
        - shell
    - role: vscode
      tags:
        - editor
    - role: vim
      tags:
        - editor
    - role: geerlingguy.docker
      become: true
      tags:
        - docker
    - role: quality_of_life
      become: true
      tags:
        - qol
    - role: projects
      tags:
        - projects
    - role: rvm.ruby
      vars:
        rvm1_rubies: ['ruby-2.7.1']
        rvm1_user: "{{ lookup('env','USER') }}"
      tags:
        - ruby
    - role: fubarhouse.golang
      vars:
        go_version: 1.14.3
        GOPATH: "/home/{{ lookup('env','USER') }}/go"
        GOROOT: /usr/local/go
      become: true
      tags:
        - golang
